install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - pacman -S base-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - git submodule update --init --recursive

build: false

test_script:
  - cargo build
  - cargo test --verbose
